name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 5 * * *'
jobs:
  Test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            jdk: 11
          - os: ubuntu-latest
            jdk: 21
          - os: windows-latest
            jdk: 11
    #          - os: macos-latest
    #            jdk: 11
    name: Run tests
    runs-on: ${{ matrix.os }}
    env:
      CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
      CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: temurin
          server-id: central
          server-username: ${{ secrets.CENTRAL_USERNAME }}
          server-password: ${{ secrets.CENTRAL_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Run tests
        run: mvn -s .github/maven-ci-settings.xml -q clean verify -B -Dgpg.skip
